#!/bin/bash


# This script is a wrapper for the entire analysis pipeline.
# INPUT:
#   CONFIG_PATH = Full path to config.yaml file in DeepLabCut2 project directory
#   VIDEO_DIRECTORY = Full path to directory containing videos you want to analyze
#   NETWORK_NAME = Full name of the DeepLabCut2 network being used to analyze the videos
#
# 1.
#   The script will find .avi files in the supplied video directory and run DeepLabCut's video analysis
#   function on each one. It will use the DeepLabCut2 project and network specified by <CONFIG_PATH> and <NETWORK_NAME>.
#
# 2.
#   After the DLC analysis finishes for a given video, kinalyze.py is run on the video and corresponding h5 output
#   to isolate all the reaches that happened in that video and generate 3D trajectory reconstructions for each reach.
#   It saves all the reaching data for each video into a text file specific to that video.
#
# 3. remakeVideo.py is then called, which uses the text file generated by kinalyze.py to cut out all frames
#    from the video that are not within the frame index bounds of a reaching event. It concatenates all the
#    reaches together into a single video that jumps from reach to reach, updating the frame indexes in the
#    corresponding data file accordingly.
#
# 4. (NOT CURRENTLY IN USE).
#    analysis.py is then called, which uses the output of kinalyze.py to predict the trial outcome for each reach.
#
# 5. All the data generated for the current video is then packaged into a folder called
#    <HomeCageSinglePellet/AnimalProfiles/<animal_name>/Analyses/<video_name>/
#    This directory contains the video file (cut to eliminate garbage video), the raw h5 deeplabcut output,
#    and a file containing the reach trajectory reconstruction vectors, frame start/stop indexes
#    and trial outcome for every reach in that video.
#
# 6. Repeat for each video found.

CONFIG_PATH=$1
VIDEO_DIRECTORY=$2
NETWORK_NAME=$3

for video in $VIDEO_DIRECTORY*.avi
do
	echo $video
	source activate DLC2
	python /home/sliasi/.conda/envs/DLC2/lib/python3.6/site-packages/deeplabcut/HCSP_analyze.py analyze-videos $CONFIG_PATH $video 

	source activate HCSP
	videoExtensionRemoved=${video::-4}
	python kinalyze.py $video $videoExtensionRemoved$NETWORK_NAME.h5 $videoExtensionRemoved"_reaches.txt" 0 0 0 1 0 

    # franks stuff
    python remakeVideo.py
    python analysis.py

	mv $video $VIDEO_DIRECTORY"../Temp/"
	mv $videoExtensionRemoved$NETWORK_NAME.h5 $VIDEO_DIRECTORY"../Temp/"
	mv $videoExtensionRemoved$NETWORK_NAME.csv $VIDEO_DIRECTORY"../Temp/"
	mv $videoExtensionRemoved"_reaches.txt" $VIDEO_DIRECTORY"../Temp/"
	rm $VIDEO_DIRECTORY*".pickle"

	cd $VIDEO_DIRECTORY"../Temp/"
	vidExtRmvd=""
	for vid in ./*.avi
	do
		vidExtRmvd=${vid::-4}
		mkdir ../Analyses/$vidExtRmvd
		cd ../Analyses/$vidExtRmvd

	done

	for file in ../../Temp/*
	do
		mv $file ./
	done
	cd ../../../../src/analysis/
		

done
